service: be
package:
  individually: true
provider:
  name: aws
  profile: ${opt:aws-profile, "ntuscse"}
  region: "ap-southeast-1"
  stage: ${opt:stage, "dev"}
  runtime: python3.9

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-lift
custom:
  pythonRequirements:
    dockerizePip: false
    usePoetry: true
  serverless-offline:
    allowCache: true
    useChildProcesses: true
    httpPort: 4000

functions:
  root:
    handler: be.root.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: get
          path: /

  getUsers:
    handler: be.api.v1.endpoints.users.get.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: get
          path: /users
      - http:
          method: get
          path: /users/{proxy+}

  getProducts:
    handler: be.api.v1.endpoints.products.get.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: get
          path: /products
      - http:
          method: get
          path: /products/{proxy+}

  preSignUp:
    handler: be.auth.v1.pre_sign_up.lambda_handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - cognitoUserPool:
          pool: SCSEAuth
          trigger: PreSignUp

constructs:
  myTable:
    type: database/dynamodb-single-table


resources:
  Resources:
    CognitoUserPoolSCSEAuth:
      Type: AWS::Cognito::UserPool
      Properties:
        # Generate a name based on the stage
        UserPoolName: ${self:provider.stage}-user-pool
        # Set email as an alias
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: "family_name"
            Required: true
            Mutable: true
          - Name: "given_name"
            Required: true
            Mutable: true
          - Name: "updated_at"
            Required: true
            Mutable: true
        

    CognitoUserPoolClientSCSEAuth:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        # Generate an app client name based on the stage
        ClientName: ${self:provider.stage}-user-pool-client
        UserPoolId:
          Ref: CognitoUserPoolSCSEAuth
        GenerateSecret: true
        AllowedOAuthFlows: 
          - code
        AllowedOAuthScopes: 
          - email
          - openid
        CallbackURLs: 
          - https://google.com
        