# sls deploy --stage dev

name: Deploy (dev)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # allows writing openid token for aws

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: ./poetry_virtualenv
          installer-parallel: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::188191680553:role/github_actions
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: npm run setup

      - name: Deploy to AWS
        run: |
          sls deploy --stage dev